Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'EC2 Configuration Parameters'
        Parameters:
          - InstanceType
          - ImageId
    ParameterLabels:
      InstanceType:
        default: 'Type of EC2 instance to launch'
      ImageId:
        default: 'Type of EC2 instance Image'

Parameters:
  InstanceType:
    Type: String
    Description: 'EC2 instance type'
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t3.medium
      - t3.large
  ImageId:
    Type: AWS::EC2::Image::Id
    Description: 'select the os image'


Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId
      Tags: 
        - Key: Name 
          Value: !Join ['-',[!Ref InstanceType, server-node]]
        - Key: InstanceType
          Value: !Sub '${InstanceType}-sever'
