Metadata: 
    AWS::CloudFormation::Interface:  
        ParameterGroups: 
            - Label: 
                Default: EC2 Configurations
              Parameters: 
                - InstanceType 
        
        ParameterLabels: 
             InstanceType: 
               Default: Type of ec2 instance 

Parameters: 
  InstanceType: 
     Type: String 
     Description: Size of instance to launch
     Default: t3.micro 
     AllowedValues:
        - t3.micro 
        - t3.medium 
        - t3.large

Outputs: 
  InstancePublicDNSName: 
     Description: PublicDnsName 
     Value: !GetAtt Ec2Instance.PublicIp
  InstanceId: 
    Description: ec2-instanceId
    Value: !Ref Ec2Instance
  SgroupId: 
    Description: SecurityGroupID 
    Value: !GetAtt SGroup.GroupId


Resources: 
  Ec2Instance: 
    Type: AWS::EC2::Instance 
    Properties: 
       InstanceType: !Ref InstanceType
       ImageId: ami-04a81a99f5ec58529
       SecurityGroupIds: 
          - !GetAtt SGroup.GroupId
  SGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Allow http to client host
      VpcId: vpc-0f9895e367d21b805
      SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            CidrIp: 0.0.0.0/0 
      SecurityGroupEgress:
          - IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            CidrIp: 0.0.0.0/0