Metadata: 
  AWS::CloudFormation::Interface: 
     ParameterGroups: 
        - Label: 
            Default: EC2 configurations
          Parameters: 
            - AmiId 
            - InstanceType 
     ParameterLabels: 
         AmiId: 
           Default: image that needs to launch 
         InstanceType: 
           Default: size of instance to launch 

Parameters: 
  AmiId: 
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Description: Type of OS to launch 
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  InstanceType: 
    Type: String 
    Default: t3.micro 
    AllowedValues: 
      - t3.micro 
      - t3.medium 
      - t3.large


Resources: 
  Ec2Launch:
    Type: AWS::EC2::Instance 
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref  AmiId

