Metadata: 
   AWS::CloudFormation::Interface:
         ParameterGroups: 
             - Label: 
                 Default: RDS configurations 
               Parameters: 
                  - DBInstanceID
                  - DBName
                  - DBInstanceClass
                  - DBAllocatedStorage
                  - DBUsername
                  - DBPassword
         ParameterLabels: 
              DBInstanceID: 
                 Default: ID of DB Instance 
              DBName: 
                Default: DB Name 
              DBInstanceClass: 
                Default: Size of DB Instance 
              DBAllocatedStorage: 
                Default: Storage Allocation 
              DBUsername: 
                Default: Username of DB 
              DBPassword: 
                Default: Password of DB
                 
Parameters:
  DBInstanceID:
    Default: mydbinstance
    Description: My database instance
    Type: String
  DBName:
    Default: mydb
    Description: My database
    Type: String
  DBInstanceClass:
    Default: db.m5d.large
    Description: DB instance class
    Type: String
  DBAllocatedStorage:
    Default: '25'
    Description: The size of the database (GiB)
    Type: Number
  DBUsername:
    NoEcho: 'true'
    Description: Username for MySQL database access
    Type: String 
  DBPassword:
    NoEcho: 'true'
    Description: Password MySQL database access
    Type: String
  


Resources:
  MyDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceID
      DBName: !Ref DBName
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      Engine: MySQL
      EngineVersion: "8.0.35"
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword